### ISSUE TITLE
Patcher crashes

### ISSUE THREAD

**Issue by aJrenalin** [panthuncia/CACO_Patcher#2]
for whatever reason this patcher crashes for me. I get the following error:

RecordException  => MAG_FrostDamageFFHazardArea (0B79FE:Skyrim.esm<MagicEffect>): Specified argument was out of the range of valid values. (Parameter 'length') System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'length')
   at Mutagen.Bethesda.Skyrim.MagicEffectBinaryOverlay.<>c.<FillRecordType>b__285_1(ReadOnlyMemorySlice`1 s, BinaryOverlayFactoryPackage p)
   at Mutagen.Bethesda.Plugins.Binary.Overlay.BinaryOverlayList.BinaryOverlayListByStartIndex`1.GetEnumerator()+MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at Noggog.EnumerableExt.ToExtendedList[T](IEnumerable`1 e) in D:\a\CSharpExt\CSharpExt\Noggog.CSharpExt\Extensions\EnumerableExt.cs:line 272
   at Mutagen.Bethesda.Skyrim.MagicEffectSetterTranslationCommon.DeepCopyIn(IMagicEffect item, IMagicEffectGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
   at Mutagen.Bethesda.Skyrim.MagicEffectSetterTranslationCommon.DeepCopyIn(IMajorRecord item, IMajorRecordGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
   at Mutagen.Bethesda.Skyrim.SkyrimMajorRecordSetterTranslationCommon.DeepCopyIn(ISkyrimMajorRecordInternal item, ISkyrimMajorRecordGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
   at Mutagen.Bethesda.Skyrim.MagicEffectSetterTranslationCommon.DeepCopyIn(IMagicEffectInternal item, IMagicEffectGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
   at Mutagen.Bethesda.Skyrim.MagicEffectSetterTranslationCommon.DeepCopyIn(IMajorRecordInternal item, IMajorRecordGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
   at Mutagen.Bethesda.Plugins.Records.MajorRecordSetterTranslationCommon.DeepCopy(IMajorRecordGetter item, TranslationMask copyMask)
   at Mutagen.Bethesda.OverrideMixIns.GetOrAddAsOverride[TMajor,TMajorGetter](IGroup`1 group, TMajorGetter major)   at Mutagen.Bethesda.OverrideMixIns.GetOrAddAsOverride[TMajor,TMajorGetter](IGroup`1 group, TMajorGetter major)
   at CACO_Patcher.Program.patchMagicEffects(IPatcherState`2 state, List`1 modNames, List`1 mods) in C:\Users\User-PC\AppData\Local\Temp\Synthesis\96432700-7ec0-4afa-88b4-8b05354bb2a8\Git\f0tx5dwj.ozk\Runner\CACO_Patcher\Program.cs:line 558
   at CACO_Patcher.Program.RunPatch(IPatcherState`2 state) in C:\Users\User-PC\AppData\Local\Temp\Synthesis\96432700-7ec0-4afa-88b4-8b05354bb2a8\Git\f0tx5dwj.ozk\Runner\CACO_Patcher\Program.cs:line 97
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass15_0`2.<<AddPatch>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 103
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, Nullable`1 exportKey, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 607
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass43_0.<<Run>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 472
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.HandleOnShutdown(Func`1 a) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 833
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 460
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass42_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 432

**Comment by aJrenalin** [comment]
since the record exception was a magic effect I used the settings to disable patching of magic effects but now I get this error: 

System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Noggog.ListExt.SetTo[T](IList`1 list, IEnumerable`1 items, Boolean checkEquality) in D:\a\CSharpExt\CSharpExt\Noggog.CSharpExt\Extensions\ListExt.cs:line 195
   at CACO_Patcher.Program.patchNpcs(IPatcherState`2 state, List`1 modNames, List`1 mods) in C:\Users\User-PC\AppData\Local\Temp\Synthesis\96432700-7ec0-4afa-88b4-8b05354bb2a8\Git\f0tx5dwj.ozk\Runner\CACO_Patcher\Program.cs:line 685
   at CACO_Patcher.Program.RunPatch(IPatcherState`2 state) in C:\Users\User-PC\AppData\Local\Temp\Synthesis\96432700-7ec0-4afa-88b4-8b05354bb2a8\Git\f0tx5dwj.ozk\Runner\CACO_Patcher\Program.cs:line 103
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass15_0`2.<<AddPatch>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 103
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, Nullable`1 exportKey, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 607
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass43_0.<<Run>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 472
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.HandleOnShutdown(Func`1 a) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 833
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 460
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass42_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 432

**Comment by aJrenalin** [comment]
seems to only work when I've disabled both the patching of NPCs and Magic effects
